spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testdb?useSSL=false
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        generate-ddl: true